layers:
  # if conv: ["conv", inchans, outchans, ksize, stride]
  # if res: ["res", [inchans...], [outchans...], [ksizes...], repeats, store_output]
  1: ["conv", 3, 32, 3, 1]
  2: ["conv", 32, 64, 3, 2]
  3: ["res", [64, 32], [32, 64], [1, 3], 1, false]
  4: ["conv", 64, 128, 3, 2]
  5: ["res", [128, 64], [64, 128], [1, 3], 2, false]
  6: ["conv", 128, 256, 3, 2]
  7: ["res", [256, 128], [128, 256], [1, 3], 8, true]
  8: ["conv", 256, 512, 3, 2]
  9: ["res", [512, 256], [256, 512], [1, 3], 8, true]
  10: ["conv", 512, 1024, 3, 2]
  11: ["res", [1024, 512], [512, 1024], [1, 3], 4, true]
nclasses: 20
nanchors: 3
nbbvals: 5